version: '3.8'

services:
  web:
    build: .
    container_name: flask_app
    ports:
      - "5000:5000"
    env_file:
      - .env
    depends_on:
      flask_sqlmodel_db:
        condition: service_healthy
    volumes:
      - .:/app
    restart: unless-stopped

  flask_sqlmodel_db:
    container_name: flask_sqlmodel_db
    image: postgres:13-alpine
    env_file:
      - .env
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER}"]
      interval: 10s
      timeout: 5s
      retries: 5
    restart: unless-stopped

  tailwind:
    container_name: tailwind_builder
    build:
      context: ./frontend
    command: npx tailwindcss -i ./input.css -o ../app/static/css/output.css --watch
    working_dir: /app/frontend
    volumes:
      - .:/app
    restart: unless-stopped

volumes:
  postgres_data: {}
