services:
  flask_app:
    container_name: flask_app
    image: francescocxx/flask_live_app:0.0.1
    build: .
    ports:
      - "4000:4000"  # Maps host:container port
    environment:
      - DB_URI=postgresql://postgres:postgres@flask_db:5432/postgres  # Fixed URI
    depends_on:
      - flask_db  # Ensures DB starts first

  flask_db:
    container_name: flask_db
    image: postgres:13
    ports:
      - "5432:5432"  # Exposes PostgreSQL port
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=postgres
    volumes:
      - pg_data:/var/lib/postgresql/data  # Persistent storage

volumes:
  pg_data: {}  # Declares a named volume