<<<<<<< HEAD
version: '3.8'

services:
  web:
    build: .
    ports:
      - "5000:5000"
    environment:
      - DATABASE_URL=postgresql://postgres:postgres@flask_sqlmodel_db:5432/FlaskSQLModel_db
    depends_on:
      - flask_sqlmodel_db
    volumes:
      - .:/app
    restart: unless-stopped

  flask_sqlmodel_db:
    container_name: flask_sqlmodel_db
    image: postgres:13-alpine
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=FlaskSQLModel_db
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    restart: unless-stopped

volumes:
  postgres_data: {}
=======
services:
  flask_app:
    container_name: flask_app
    image: francescocxx/flask_live_app:0.0.1
    build: .
    ports:
      - "4000:4000"  # Maps host:container port
    environment:
      - DB_URI=postgresql://postgres:postgres@flask_db:5432/postgres  # Fixed URI
    depends_on:
      - flask_db  # Ensures DB starts first

  flask_db:
    container_name: flask_db
    image: postgres:13
    ports:
      - "5432:5432"  # Exposes PostgreSQL port
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=postgres
    volumes:
      - pg_data:/var/lib/postgresql/data  # Persistent storage

volumes:
  pg_data: {}  # Declares a named volume
>>>>>>> 4660c4ecedfa9aeada716089af7021279595ffa8
